BEGIN TRANSACTION;
PRAGMA foreign_keys=on;

DROP TABLE IF EXISTS Results_values;
DROP TABLE IF EXISTS Tolerance_params_values;
DROP TABLE IF EXISTS Tolerance_params;
DROP TABLE IF EXISTS Results;
DROP TABLE IF EXISTS Verifications;
DROP TABLE IF EXISTS Elements;
DROP TABLE IF EXISTS Devices;

CREATE TABLE [Devices] (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
NameOfDevice TEXT, 
TypeOfDevice TEXT,  
SerialNumber TEXT, 
Owner TEXT, 
GosNumber TEXT);

CREATE TABLE [Elements] (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
DeviceId INTEGER,
ElementType TEXT, 
ElementSerNumber TEXT, 
PoleCount INTEGER, 
MeasUnit TEXT, 
ModuleToleranceType TEXT, 
PhaseToleranceType TEXT, 
NominalId INTEGER,
FOREIGN KEY (DeviceId) REFERENCES Devices(id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (NominalId) REFERENCES Results(id) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE [Verifications] (
id	INTEGER PRIMARY KEY AUTOINCREMENT,
DeviceId INTEGER,
VerificationDate TEXT,
PathOfDoc TEXT,
PathOfProtocol TEXT,
TypeOfDoc TEXT,
FOREIGN KEY (DeviceId) REFERENCES Devices(id) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE [Results] (
id INTEGER PRIMARY KEY AUTOINCREMENT,
ElementId INTEGER,
MeasDate TEXT,
FOREIGN KEY (ElementId) REFERENCES Elements(id) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE [Results_values] (
id INTEGER PRIMARY KEY AUTOINCREMENT,
ResultId INTEGER, freq REAL,
MODULE_S11 REAL, ERROR_MODULE_S11 REAL, PHASE_S11 REAL, ERROR_PHASE_S11 REAL,
MODULE_S12 REAL, ERROR_MODULE_S12 REAL, PHASE_S12 REAL, ERROR_PHASE_S12 REAL,
MODULE_S21 REAL, ERROR_MODULE_S21 REAL, PHASE_S21 REAL, ERROR_PHASE_S21 REAL, 
MODULE_S22 REAL, ERROR_MODULE_S22 REAL, PHASE_S22 REAL, ERROR_PHASE_S22 REAL,
FOREIGN KEY (ResultId) REFERENCES Results(id) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE [Tolerance_params] (id INTEGER PRIMARY KEY AUTOINCREMENT,
ElementId INTEGER,
Type TEXT,
FOREIGN KEY (ElementId) REFERENCES Elements(id) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE [Tolerance_params_values] (id INTEGER PRIMARY KEY AUTOINCREMENT,
ToleranceParamsId INTEGER, freq REAL,
DOWN_MODULE_S11 REAL, UP_MODULE_S11 REAL, DOWN_PHASE_S11 REAL, UP_PHASE_S11 REAL,
DOWN_MODULE_S12 REAL, UP_MODULE_S12 REAL, DOWN_PHASE_S12 REAL, UP_PHASE_S12 REAL,
DOWN_MODULE_S21 REAL, UP_MODULE_S21 REAL, DOWN_PHASE_S21 REAL, UP_PHASE_S21 REAL, 
DOWN_MODULE_S22 REAL, UP_MODULE_S22 REAL, DOWN_PHASE_S22 REAL, UP_PHASE_S22 REAL,
FOREIGN KEY (ToleranceParamsId) REFERENCES Tolerance_params(id) ON UPDATE CASCADE ON DELETE CASCADE);

COMMIT;